### ISSUE TITLE
小伙伴好像没有后台播放

### ISSUE THREAD

**Issue by shuaiyinoo** [huangxuan518/HXMusicPlayer#1]
音乐在后台的时候就自动停止了

**Comment by huangxuan518** [comment]
对,没有做后台播放以及耳机控制的相关功能,后面有时间,可能会补充进来

**Comment by huangxuan518** [comment]
@shuaiyinoo  对,没有做后台播放以及耳机控制的相关功能,后面有时间,可能会补充进来

**Comment by shuaiyinoo** [comment]
好像这个类做后台播放很麻烦

Sent from Mail Master
在2016年04月08日 12:50，IT小子-黄轩 写道:

对,没有做后台播放以及耳机控制的相关功能,后面有时间,可能会补充进来

**Comment by huangxuan518** [comment]
@shuaiyinoo  已增加后台播放和耳机控制，不过好像有些小BUG，待完善
