### ISSUE TITLE
关于在线音乐播放问题

### ISSUE THREAD

**Issue by tianxin1989** [huangxuan518/HXMusicPlayer#2]
好像不能播放在线音乐？为什么我的在线音乐播放不出来？
<img width="673" alt="b7ebd313-feeb-4871-b4c8-92a4aa34319d" src="https://cloud.githubusercontent.com/assets/13825419/17723503/36be9d86-646d-11e6-9804-ce29d310ad25.png">

**Comment by huangxuan518** [comment]
@tianxin1989  请检查下你的音频文件是否是正常的，我看你的音频地址是ip地址，最新的苹果IPv6 ip是直接访问不了的，我不知道你的情况是否和这个有关。你看我的demo中用的是网易音乐的抓包地址，都是可以播放的，比如http://m2.music.126.net/dUZxbXIsRXpltSFtE7Xphg==/1375489050352559.mp3，你可以测试下
